export const POST_NEW_QUIZ_REQUEST = 'POST_NEW_QUIZ_REQUEST';
export const POST_NEW_QUIZ_SUCCESS = 'POST_NEW_QUIZ_SUCCESS';
export const POST_NEW_QUIZ_ERROR = 'POST_NEW_QUIZ_ERROR';
export const RESET_QUIZ = 'RESET_QUIZ';